apiVersion: v1
kind: BuildConfig
metadata:
  name: cool-app-configmap-pipeline
  labels:
    name: cool-app-configmap-pipeline
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node ("maven") {                        
          stage ("Update configmap PROD") {            
            dir ('configuration') {              
              sh "curl https://raw.githubusercontent.com/eljeko/ocp-release-pipeline-sample/master/config-map/configuration/description.properties -o description.properties"
              sh "curl https://raw.githubusercontent.com/eljeko/ocp-release-pipeline-sample/master/config-map/configuration/headers.properties -o headers.properties"            
            }            
            dir ('/tmp/workspace/cicd-cool-app-configmap-pipeline') {              
              sh "oc create configmap cool-app-config --from-file=configuration --dry-run -o yaml|oc replace -n cool-app-prod -f -"
            }
          }         
        }