apiVersion: v1
kind: Service
metadata: 
  labels:
    app: acmeapp-blue
    app.kubernetes.io/component: acmeapp-blue
    app.kubernetes.io/instance: acmeapp-blue
  name: acmeapp-blue  
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deploymentconfig: acmeapp-blue
  sessionAffinity: None
  type: ClusterIP